mate-screenshot/screenshot-dialog.c
Backport of https://github.com/mate-desktop/mate-utils/pull/81 to 1.8 branch.
=> [1.8] mate-screenshot: show the actual error message when UI load fails

baobab/data/Makefile.am, baobab/data/org.mate.disk-usage-analyzer.gschema.xml.in, configure.ac, logview/data/Makefile.am, logview/data/org.mate.system-log.gschema.xml.in, mate-dictionary/data/Makefile.am, mate-dictionary/data/org.mate.dictionary.gschema.xml.in, mate-screenshot/Makefile.am, mate-screenshot/org.mate.screenshot.gschema.xml.in, po/POTFILES.in
taken from:
https://github.com/mate-desktop/eom/commit/a2055e1
- bumped required intltool version to 0.50.1
- renamed and corrected gschema xml for proper intltool usage
- sorted lines in po/POTFILES.in (as requested in the header)
=> fixes for gschema translation

baobab/src/baobab.c, baobab/src/callbacks.c
fixes https://github.com/mate-desktop/mate-utils/issues/103
@stefano-k @flexiondotorg 
the name is the same as used before, but the place in code is different, so I guess this will require a sync with transifex for correct l10n
=> disk usage analyzer: use correct application name, not "Baobab"

configure.ac, mate-dictionary/libgdict/mate-dict.pc.in
If the package is built against gtk-3.0 (as in
./configure --with-gtk=3.0), mate-dict.pc still wants gtk-2.0
since it's hardcoded it there. This can lead to improper builds
of packages using libmatedict (although I can't find any now),
as well as improper RPM dependencies, like this:
$ rpm -e gtk2-devel
error: Failed dependencies:
...
pkgconfig(gtk+-2.0) is needed by (installed) mate-utils-devel-1.14.0-1gtk3.fc23.x86_64
Fortunately, the file is already generated, so it's trivial to add
a proper substitution.
Signed-off-by: Kir Kolyshkin <kir@openvz.org>
=> mate-dict.pc: depend upon proper gtk version

mate-dictionary/src/gdict-window.c
Fix GTK 3.21 segfault caused by issue with calling gtk_widget_realize at this point in the program. Show the widget instead as this does the same thing implicitly and doesn't segfault. Restrict this to GTK 3.21 for now. Mate-dictionary windows haven't resized to fit text all the way back to MATE 1.10 as tested with GTK 3.14, so this whole function needs to either be fixed or removed. My earlier prevented it from being called by disabling a function that used GtkStyle but in this case GtkStyle isn't causing trouble -yet.
=> Dictionary: Fix Gtk3.21 segfault

mate-screenshot/src/mate-screenshot.c
See #166. It was a bad idea to translate the timestamp. It had been fixed in gnome-screenshot, now it's time for us to do the same.
=> screenshot: don't translate the timestamp in the filename

mate-dictionary/src/gdict-applet.c, mate-screenshot/src/screenshot-utils.c
avoid deprecated:
gdk_screen_get_monitor_geometry
gdk_screen_get_monitor_at_window
=> gtk 3.22: avoid deprecated gdk_screen_get_monitor... functions:

mate-dictionary/src/gdict-aligned-window.c, mate-screenshot/src/screenshot-utils.c
This commit reverts:
https://github.com/mate-desktop/mate-utils/commit/b210e404823cb5b1fa5b74d700fa3f89c2ea71a2
https://github.com/mate-desktop/mate-utils/commit/c0b5081bf32ee22094e15c5d76a8ac8e5806e4a5
And it applies an alternative to fix the deprecated functions:
gkd_screen_width
gdk_screen_height
gdk_screen_get_width
gdk_screen_get_height
=> WidthOfScreen and HeightOfScreen implementation

mate-screenshot/data/mate-screenshot.ui, mate-screenshot/src/mate-screenshot.c, mate-screenshot/src/screenshot-dialog.h
I need to capture numerous screenshots or reselect the area. For this I needed to be constantly opening and closing the mate-screenshot application. I made this improvement to increase my productivity.
Any questions I am available.
Best regards
=> mate-screenshot: added New button

mate-dictionary/src/gdict-pref-dialog.c
seems since the commit https://github.com/mate-desktop/mate-utils/commit/c0800eff5739c3891375d5c4d1db62720fd877cd we have a memory leak
according to the documentation, `gtk_font_chooser_get_font` needs to be freed
https://developer.gnome.org/gtk3/stable/GtkFontChooser.html#gtk-font-chooser-get-font
=> mate-dictionary: Fix memory leak

baobab/help/C/index.docbook, gsearchtool/help/C/index.docbook, logview/help/C/index.docbook, mate-dictionary/docs/reference/gdict/gdict-docs.sgml, mate-dictionary/help/C/index.docbook
fix validate errors:
$ find . -name "index.docbook" -exec yelp-check validate {} \;
validity error : Element othercredit content does not follow the DTD, expecting (honorific | firstname | surname | lineage | othername | affiliation | authorblurb | contrib)+, got (personname email )
=> help - bump docbook 4.5

baobab/src/baobab.c
To detect the memory leak using valgrind:
export CFLAGS="-Og -g -fno-omit-frame-pointer -fPIE -pie"
export CXXFLAGS="-Og -g -fno-omit-frame-pointer -fPIE -pie"
./autogen.sh --prefix=/usr
make clean
make
sudo make install
valgrind --tool=memcheck --undef-value-errors=no --leak-check=full --log-file="report.txt" /usr/bin/mate-disk-usage-analyzer
report.txt content:
==16061== 6 bytes in 1 blocks are definitely lost in loss record 174 of 14,390
==16061==    at 0x483880B: malloc (vg_replace_malloc.c:309)
==16061==    by 0x56B10D7: g_malloc (gmem.c:99)
==16061==    by 0x56CAAEE: g_strdup (gstrfuncs.c:363)
==16061==    by 0x56E3743: g_variant_dup_string (gvariant.c:1533)
==16061==    by 0x5509DE6: g_settings_get_string (gsettings.c:1795)
==16061==    by 0x115664: initialize_charts …
=> mate-disk-usage-analyzer: Memory leak

baobab/src/baobab-remote-connect-dialog.c, baobab/src/baobab.c, gsearchtool/libmateui-deprecated/gsearchtool-entry.c, gsearchtool/src/gsearchtool-callbacks.c, gsearchtool/src/gsearchtool.c, logview/src/logview-app.c, logview/src/logview-log.c, logview/src/logview-manager.c, logview/src/logview-prefs.c, mate-dictionary/libgdict/gdict-client-context.c, mate-dictionary/libgdict/gdict-context.c, mate-dictionary/libgdict/gdict-defbox.c, mate-dictionary/libgdict/gdict-source-loader.c, mate-dictionary/src/gdict-app.c, mate-dictionary/src/gdict-sidebar.c
```shell
export CFLAGS="-Werror=cast-function-type -Wno-deprecated-declarations"
./autogen.sh --prefix=/usr
make
sudo make install
```
=> Fix -Werror=cast-function-type with GCC 8

baobab/data/mate-disk-usage-analyzer.appdata.xml.in, configure.ac, gsearchtool/data/mate-search-tool.appdata.xml.in, mate-dictionary/data/mate-dictionary.appdata.xml.in, mate-screenshot/data/mate-screenshot.appdata.xml.in
Now the official web site is https://mate-desktop.org/.
=> Change url project's website

baobab/src/baobab.c
Before "... (used: 9.3 GB available: 51.5 GB )"
After "... (used: 9.4 GB available: 51.4 GB)"
=> mate-disk-usage-analyzer: Remove blank space before right parenthesis

logview/src/logview-window.c
Status bar date&time.
- Use g_date_time_format instead of strftime
- %c: the preferred date and time representation for the current locale
Before:
After:
=> logview: Use preferred date&time representation for current locale

baobab/src/baobab-chart.c, baobab/src/baobab-remote-connect-dialog.c, baobab/src/baobab-ringschart.c, baobab/src/baobab-treemap.c, gsearchtool/src/gsearchtool-callbacks.c
Fixes the warnings:
```
baobab-ringschart.c:77:13: warning: redundant redeclaration of 'baobab_ringschart_class_init' [-Wredundant-decls]
baobab-ringschart.c:78:13: warning: redundant redeclaration of 'baobab_ringschart_init' [-Wredundant-decls]
baobab-remote-connect-dialog.c:60:42: warning: redundant redeclaration of 'baobab_remote_connect_dialog_init' [-Wredundant-decls]
baobab-remote-connect-dialog.c:60:42: warning: redundant redeclaration of 'baobab_remote_connect_dialog_class_init' [-Wredundant-decls]
baobab-chart.c:105:13: warning: redundant redeclaration of 'baobab_chart_class_init' [-Wredundant-decls]
baobab-chart.c:106:13: warning: redundant redeclaration of 'baobab_chart_init' [-Wredundant-decls]
baobab-treemap.c:56:13: warning: redundant redeclaration of …
```
=> avoid redundant redeclarations

mate-screenshot/data/mate-screenshot.ui
The position of the GtkButton `new_button` wasn't established, so the buttons order was changed after saving the ui file on glade. Now the position of the GtkButton `new_button` is set to 4.
=> mate-screenshot: do not use stock icons in mate-screenshot.ui

baobab/src/baobab.c
```
baobab.c:736:10: warning: unused variable ‘uri_list’ [-Wunused-variable]
736 |  GSList *uri_list = NULL;
|          ^~~~~~~~
```
=> baobab: Remove unused variable ‘uri_list’

mate-dictionary/src/gdict-applet.c
```
gdict-applet.c:106:20: warning: ‘n_drop_types’ defined but not used [-Wunused-const-variable=]
106 | static const guint n_drop_types = G_N_ELEMENTS (drop_types);
|                    ^~~~~~~~~~~~
```
=> mate-dictionary: warning ‘n_drop_types’ defined but not used

logview/src/logview-app.c, mate-screenshot/src/mate-screenshot.c
```
mate-screenshot.c:123:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
123 | void loop_dialog_screenshot ();
| ^~~~
mate-screenshot.c:1251:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
1251 | loop_dialog_screenshot ()
| ^~~~~~~~~~~~~~~~~~~~~~
logview-app.c:97:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
97 | parse_syslog ()
| ^~~~~~~~~~~~
```
=> Remove warnings: function declaration isn’t a prototype

mate-dictionary/src/gdict-window.c
```
./autogen.sh --enable-compile-warnings=maximum --prefix=/usr && make &> make.log
```
Removed warning:
```
gdict-window.c:256:1: warning: ‘gdict_window_set_statusbar_visible’ defined but not used [-Wunused-function]
256 | gdict_window_set_statusbar_visible (GdictWindow *window,
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> mate-dictionary: remove unused function 'gdict_window_set_statusbar_visible'

gsearchtool/src/gsearchtool-callbacks.c, gsearchtool/src/gsearchtool-callbacks.h
This PR adds the ability to copy the path to the clipboard of one selected item. When multiple rows are selected this menu item will not show up.
It is very useful when you only want the path of a file or folder for later usage in the terminal or a program.
=> Copy path option in popup menu

gsearchtool/src/gsearchtool-support.c, gsearchtool/src/gsearchtool.c, mate-screenshot/src/screenshot-dialog.c
```
screenshot-dialog.c:241:4: warning: cast from function call of type ‘int’ to non-matching type ‘float’ [-Wbad-function-cast]
241 |    (gfloat) gdk_pixbuf_get_height (screenshot),
|    ^
--
gsearchtool-support.c:856:43: warning: cast from function call of type ‘int’ to non-matching type ‘float’ [-Wbad-function-cast]
856 |     scale_factor_x = (gfloat) ICON_SIZE / (gfloat) gdk_pixbuf_get_width (thumbnail_pixbuf);
|                                           ^
gsearchtool-support.c:859:43: warning: cast from function call of type ‘int’ to non-matching type ‘float’ [-Wbad-function-cast]
859 |     scale_factor_y = (gfloat) ICON_SIZE / (gfloat) gdk_pixbuf_get_height (thumbnail_pixbuf);
|                                           ^
--
gsearchtool.c:914:28: warning: cast from function call of …
```
=> Remove bad-function-cast warnings

gsearchtool/src/gsearchtool.c
```
gsearchtool.c:928:41: warning: implicit conversion from ‘enum <anonymous>’ to ‘GFileMonitorFlags’ [-Wenum-conversion]
928 |   handle = g_file_monitor_file (g_file, G_FILE_MONITOR_EVENT_DELETED, NULL, &error);
|                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> gsearchtool: Remove enum conversion warning

baobab/help/C/index.docbook
Correct misspellings of MATE/MATE Desktop in help pages.
=> docbook: correct DE name

logview/src/tests/test-reader.c
Test on fedora:
```
$ ./logview/src/tests/test-reader -f /var/log/dnf.log.2
```
=> logview: Use test-reader test with log file path

configure.ac
```
$ grep "but option 'subdir-objects' is disabled" -B 1 mate-utils.conf.log 
logview/src/tests/Makefile.am:8: warning: source file '../logview-log.c' is in a subdirectory,
logview/src/tests/Makefile.am:8: but option 'subdir-objects' is disabled
--
logview/src/tests/Makefile.am:8: warning: source file '../logview-utils.c' is in a subdirectory,
logview/src/tests/Makefile.am:8: but option 'subdir-objects' is disabled
mate-dictionary/libgdict/Makefile.am:32: warning: source file '$(srcdir)/gdict-context.c' is in a subdirectory,
mate-dictionary/libgdict/Makefile.am:32: but option 'subdir-objects' is disabled
mate-dictionary/libgdict/Makefile.am:32: warning: source file '$(srcdir)/gdict-client-context.c' is in a subdirectory,
mate-dictionary/libgdict/Makefile.am:32: but option …
```
=> configure: remove warning about option 'subdir-objects' is disabled

mate-dictionary/src/gdict-window.c
```
gdict-window.c:1261:3: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct _GtkActionEntry'} [-Wmissing-field-initializers]
gdict-window.c:1262:3: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct _GtkActionEntry'} [-Wmissing-field-initializers]
gdict-window.c:1263:3: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct _GtkActionEntry'} [-Wmissing-field-initializers]
gdict-window.c:1264:3: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct _GtkActionEntry'} [-Wmissing-field-initializers]
gdict-window.c:1265:3: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct _GtkActionEntry'} …
```
=> gdict-window: Remove warnings about missing initializer for field

mate-dictionary/libgdict/gdict-utils.c
Test 1: debug enabled
```
$ ./autogen.sh --prefix=/usr --enable-debug && make && sudo make install
$ GDICT_DEBUG="misc,context,dict,source,loader,chooser,speller" mate-dictionary
```
Test 2: debug disabled (default)
```
$ ./autogen.sh --prefix=/usr & make && sudo make install
$ mate-dictionary
```
warning:
```
./gdict-utils.c: In function 'pre_parse_hook':
./gdict-utils.c:110:15: warning: variable 'env_string' set but not used [-Wunused-but-set-variable]
110 |   const char *env_string;
|               ^~~~~~~~~~
```
=> gdict-utils: variable 'env_string' set but not used

mate-screenshot/src/screenshot-save.c
```
screenshot-save.c: In function 'screenshot_save_start':
screenshot-save.c:221:7: warning: suggest explicit braces to avoid ambiguous 'else' [-Wdangling-else]
221 |    if (error && error->message)
|       ^
```
=> screenshot-save: warning -Wdangling-else

baobab/src/baobab-ringschart.c
```
baobab-ringschart.c: In function 'baobab_ringschart_draw_subfolder_tips':
baobab-ringschart.c:520:50: warning: left-hand operand of comma expression has no effect [-Wunused-value]
520 |       _rect.width = (int) (tooltip_rect.width + 2,0);
|                                                  ^
```
culprit #306
=> baobab: remove warning -Wunused-value

mate-screenshot/data/mate-screenshot.ui
Move the `New` button to the left, before the `Copy to Clipboard` button.
culprit https://github.com/mate-desktop/mate-utils/commit/e530494
closes #315
=> mate-screenshot: fix the order of the buttons at the bottom

baobab/src/baobab-chart.c, baobab/src/baobab-ringschart.c, baobab/src/baobab-scan.c, baobab/src/baobab-utils.c, mate-dictionary/src/gdict-sidebar.c
```
baobab-scan.c:340:1: warning: no previous prototype for ‘baobab_scan_execute’ [-Wmissing-prototypes]
baobab-ringschart.c:367:1: warning: no previous prototype for ‘baobab_ringschart_subfolder_tips_timeout’ [-Wmissing-prototypes]
baobab-ringschart.c:381:1: warning: no previous prototype for ‘baobab_ringschart_clean_subforlder_tips_state’ [-Wmissing-prototypes]
baobab-utils.c:73:1: warning: no previous prototype for ‘filechooser_cb’ [-Wmissing-prototypes]
baobab-chart.c:1174:1: warning: no previous prototype for ‘baobab_chart_get_pixbuf’ [-Wmissing-prototypes]
gdict-sidebar.c:75:1: warning: no previous prototype for ‘sidebar_page_new’ [-Wmissing-prototypes]
gdict-sidebar.c:93:1: warning: no previous prototype for ‘sidebar_page_free’ [-Wmissing-prototypes]
```
=> Remove warnings about missing prototypes

logview/src/logview-log.c
test
```
grep -R -w "^[[:space:]]*#if\|^[[:space:]]*#else\|[[:space:]]*#endif\|[[:space:]]*#ifdef\|#define" --include *.c | grep -F ": "
```
=> logview: remove whitespaces before #if, #else, and #endif

mate-screenshot/src/mate-screenshot.c
Test:
```
gsettings set org.mate.screenshot last-save-directory ''
```
```
LeakSanitizer: detected memory leaks
Direct leak of 1 byte(s) in 1 object(s) allocated from:
#0 0x7f860bd0193f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7f860ab424ff in g_malloc ../glib/gmem.c:106
#2 0x7f860ab42842 in g_malloc_n ../glib/gmem.c:344
#3 0x7f860ab64d85 in g_strdup ../glib/gstrfuncs.c:364
#4 0x7f860ab930d4 in g_variant_dup_string ../glib/gvariant.c:1543
#5 0x7f860adf8aed in g_settings_get_string ../gio/gsettings.c:1807
#6 0x40bd28 in load_options /home/robert/builddir.gcc/mate-utils/mate-screenshot/src/mate-screenshot.c:1181
#7 0x40cf31 in main /home/robert/builddir.gcc/mate-utils/mate-screenshot/src/mate-screenshot.c:1372
#8 0x7f860a7bdb74 in __libc_start_main …
```
=> mate-screenshot: fix memory leak

logview/src/logview-utils.c, mate-dictionary/libgdict/gdict-client-context.c, mate-dictionary/libgdict/gdict-source.c
`g_free` and `gdict_command_free` already check that the variable is not null before freeing memory.
=> Redundant null check before freeing the variable

gsearchtool/src/gsearchtool-support.c
```
Direct leak of 9534 byte(s) in 811 object(s) allocated from:
#0 0x7fc3c3ab393f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7fc3c2a4d1bf in g_malloc ../glib/gmem.c:106
#2 0x7fc3c2a4d502 in g_malloc_n ../glib/gmem.c:344
#3 0x7fc3c2a6f995 in g_strdup ../glib/gstrfuncs.c:364
#4 0x7fc3c2cc2d2f in g_content_type_get_description ../gio/gcontenttype.c:481
#5 0x40e88f in get_file_type_description /home/robert/builddir.gcc/mate-utils/gsearchtool/src/gsearchtool-support.c:452
#6 0x41fe9b in add_file_to_search_results /home/robert/builddir.gcc/mate-utils/gsearchtool/src/gsearchtool.c:880
#7 0x42356c in handle_search_command_stdout_io /home/robert/builddir.gcc/mate-utils/gsearchtool/src/gsearchtool.c:1566
#8 0x7fc3c2ab8c18 in g_io_unix_dispatch ../glib/giounix.c:166
#9 …
```
=> gsearchtool: fix memory leak

baobab/src/baobab.c, gsearchtool/src/gsearchtool-callbacks.c, gsearchtool/src/gsearchtool.c, logview/src/logview-main.c, mate-dictionary/libgdict/gdict-context.c, mate-dictionary/libgdict/gdict-utils.c, mate-dictionary/src/gdict-app.c, mate-disk-image-mounter/src/main.c, mate-screenshot/src/mate-screenshot.c
```
baobab.c:1226:8: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{NULL}
^
--
gdict-context.c:71:7: warning: missing field 'instance_size' initializer [-Wmissing-field-initializers]
};
^
--
gdict-utils.c:101:11: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL, },
^
--
gdict-app.c:334:12: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL },
^
--
mate-screenshot.c:1324:12: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL },
^
--
gsearchtool-callbacks.c:224:78: warning: missing field 'max_width' initializer [-Wmissing-field-initializers]
GdkGeometry default_geometry = {MINIMUM_WINDOW_WIDTH, MINIMUM_WINDOW_HEIGHT};
^
--
gsearchtool.c:178:9: warning: …
```
=> Fix build warnings about missing field initializer

logview/src/logview-app.c, logview/src/logview-log.c
```
logview-app.c:188:38: warning: converting the enum constant to a boolean [-Wint-in-bool-context]
if (type != (G_FILE_TYPE_REGULAR || G_FILE_TYPE_SYMBOLIC_LINK) ||
^
```
```
logview-log.c:646:36: warning: converting the enum constant to a boolean [-Wint-in-bool-context]
if (type != (G_FILE_TYPE_REGULAR || G_FILE_TYPE_SYMBOLIC_LINK) ||
^
```
=> logview: converting the enum constant to a boolean

baobab/src/callbacks.h
Test:
```
CFLAGS="-Werror=missing-prototypes" ./autogen.sh --prefix=/usr && make && sudo make install
```
Warnings:
```
callbacks.c:120:1: error: no previous prototype for function 'on_menu_expand_activate' [-Werror,-Wmissing-prototypes]
on_menu_expand_activate (GtkMenuItem *menuitem, gpointer user_data)
^
callbacks.c:119:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
void
^
static
```
```
callbacks.c:126:1: error: no previous prototype for function 'on_menu_collapse_activate' [-Werror,-Wmissing-prototypes]
on_menu_collapse_activate (GtkMenuItem *menuitem, gpointer user_data)
^
callbacks.c:125:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
void
^
static
```
=> baobab: Fix -Wmissing-prototypes warnings

logview/data/logview-toolbar.xml, logview/src/logview-findbar.c, logview/src/logview-log.c, logview/src/logview-window.c
Replace the deprecated API with ```GtkMenuBar``` + ```GActionGroup``` + ```GtkBuilder```  + ```gtk_tool_button_new``` + ```GTask``` fix compilation warnings，Note that I removed the ```gtk_ui_manager_set_add_tearoffs``` related features
```
logview-window.c:1135:3: warning: 'gtk_ui_manager_set_add_tearoffs' is deprecated [-Wdeprecated-declarations]
gtk_ui_manager_set_add_tearoffs (window->priv->ui_manager, TRUE);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
logview-window.c:1164:7: warning: 'gtk_action_group_get_action' is deprecated [-Wdeprecated-declarations]
action = gtk_action_group_get_action (window->priv->action_group,
^~~~~~
logview-findbar.c:200:3: warning:‘gtk_tool_button_new_from_stock’ is deprecated: Use 'gtk_tool_button_new' instead [-Wdeprecated-declarations]
priv->clear_button = …
```
=> logview: Replace deprecated functions fix compilation warnings

baobab/src/baobab-remote-connect-dialog.c
```
baobab-remote-connect-dialog.c:76:11: warning: format string is not a string literal [-Wformat-nonliteral]
error_message, NULL);
^~~~~~~~~~~~~
```
=> baobab-remote-connect-dialog: fix -Wformat-nonliteral warning

mate-dictionary/data/mate-dictionary-ui.xml, mate-dictionary/src/gdict-window.c, mate-dictionary/src/gdict-window.h
Replace the deprecated API with ```GtkMenuBar``` + ```GActionGroup``` + ```GtkBuilder``` fix compilation warnings
```
gdict-window.c:218:7: warning: 'gtk_ui_manager_get_widget' is deprecated [-Wdeprecated-declarations]
item = gtk_ui_manager_get_widget (window->ui_manager, toggle_state[i]);
gdict-window.c:218:7: warning: 'gtk_ui_manager_get_widget' is deprecated [-Wdeprecated-declarations]
item = gtk_ui_manager_get_widget (window->ui_manager, toggle_state[i]);
```
=> mate-dictionary: Replace deprecated functions fix compilation warnings

configure.ac, mate-dictionary/data/Makefile.am, mate-dictionary/data/org.mate.DictionaryApplet.mate-panel-applet.desktop.in.in, mate-dictionary/src/Makefile.am, mate-dictionary/src/gdict-aligned-window.c, mate-dictionary/src/gdict-applet.c
*In-process is needed for wayland support
*this also fixes an unresponsive response dialog out of process
*Depends on https://github.com/mate-desktop/mate-panel/pull/1400 for in-process builds to run
=> dictionary applet: allow building in-process, fix the popup response dialog

configure.ac, mate-dictionary/src/Makefile.am, mate-dictionary/src/gdict-aligned-window.c, mate-dictionary/src/gdict-applet.c
*Use gtk layer shell to duplicate the x11 behavior of the dictionary applet's popup dialog window
=> Wayland: Fix position and behavior of dictionary applet popup window

mate-dictionary/src/gdict-aligned-window.c, mate-dictionary/src/gdict-applet.c
*Move the text entry box from the panel to the popup dialog when running under wayland
*The only way we can focus it on the panel is with low level x11 code or with the keyboard 
*Leave the text entry box on the panel for x11, don't fix what isn't broken
=> wayland, dictionary: Make the panel applet usable in wayland

mate-dictionary/src/gdict-applet.c
*For a GtkButtonBox we must specify it as GTK_BUTTON_BOX (bbox) not GTK_BOX (bbox)
=> dictionary applet: fix in-process build warning

gsearchtool/data/mate-search-tool.desktop.in
With GNOME search tool being deprecated and removed from some distros therefore, how about making this app available in other desktops too?
=> search tool: show also in other desktops

mate-screenshot/data/org.mate.screenshot.gschema.xml.in, mate-screenshot/src/mate-screenshot.c
This setting allows user to enable/disable the shutter sound when taking a screenshot. Default is enabled to maintain current behavior.
Fixes #134
=> mate-screenshot: Toggle shutter sound
